<?php include('../App/Views/index/header.phtml') ?>
  
  <div class="container">

    <form id="dados" method="POST" action="<?php echo $this->view->operacao; ?>">
      <div class="form-row">
        <div class="form-group col-md-2">
          <input type="text" class="form-control form-control-sm" id="id" name="id" placeholder="ID" value="<?= isset($this->view->dadosPaciente['0']['id']) ? $this->view->dadosPaciente['0']['id'] : '' ?>" readonly>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-6">
          <input type="text" class="form-control form-control-sm" id="nome" name="nome" placeholder="Nome" value="<?= isset($this->view->dadosPaciente['0']['nome']) ? $this->view->dadosPaciente['0']['nome'] : '' ?>">
        </div>
      </div>
       
      <div class="form-row">
        <div class="form-group col-md-2">
          <select class="form-control form-control-sm" name="status" id="status" value= "<?= isset($this->view->dadosPaciente['0']['status']) ? $this->view->dadosPaciente['0']['status'] : '' ?>">
            <option value="A">Ativo</option>
            <option value="I">Inativo</option>
          </select>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-4">
          <select class="form-control form-control-sm" name="id_plano" id="id_plano" value="<?= isset($this->view->dadosPaciente['0']['id_plano']) ? $this->view->dadosPaciente['0']['id_plano'] : '' ?>"> 
            <option value="0">Planos:</option> 
            <?php if (isset($this->view->planos)) {
              foreach ($this->view->planos as $key => $value) { ?>
                <option value="<?=$value['id'] ?>"><?=$value['descricao'] ?></option> 
             <?php 
              }
            } ?>
          </select>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-4">
          <select class="form-control form-control-sm" name="id_convenio" id="id_convenio" value="<?= isset($this->view->dadosPaciente['0']['id_convenio']) ? $this->view->dadosPaciente['0']['id_convenio'] : '' ?>"> 
            <option value="0">Convênios:</option> 
            <?php if (isset($this->view->convenios)) {
              foreach ($this->view->convenios as $key => $value) { ?>
                <option value="<?=$value['id'] ?>"><?=$value['descricao'] ?></option> 
             <?php 
              }
            } ?>
          </select>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-3">
          <input type="text" class="form-control form-control-sm" id="cpf" name="cpf" placeholder="C.P.F" value="<?= isset($this->view->dadosPaciente['0']['cpf']) ? $this->view->dadosPaciente['0']['cpf'] : '' ?>">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-3">
          <input type="text" class="form-control form-control-sm" id="rg" name="rg" placeholder="R.G" value="<?= isset($this->view->dadosPaciente['0']['rg']) ? $this->view->dadosPaciente['0']['rg'] : '' ?>">
        </div>
      </div>
      
      <div class="form-row">
        <div class="form-group col-md-3">
          <input type="text" class="form-control form-control-sm" id="cns" name="cns" placeholder="Cartão SUS" value="<?= isset($this->view->dadosPaciente['0']['cns']) ? $this->view->dadosPaciente['0']['cns'] : '' ?>">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-3">
          <input type="text" class="form-control form-control-sm" id="numero_carteirinha" name="numero_carteirinha" placeholder="Número da carteirinha" value="<?= isset($this->view->dadosPaciente['0']['numero_carteirinha']) ? $this->view->dadosPaciente['0']['numero_carteirinha'] : '' ?>">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-3">
          <input type="text" class="form-control form-control-sm" id="profissao" name="profissao" placeholder="Profissão" value="<?= isset($this->view->dadosPaciente['0']['profissao']) ? $this->view->dadosPaciente['0']['profissao'] : '' ?>">
        </div>
      </div>
      
      <div class="form-row">
        <div class="form-group col-md-2">
          <select class="form-control form-control-sm" name="estado_civil" id="estado_civil" value= "<?= isset($this->view->dadosPaciente['0']['estado_civil']) ? $this->view->dadosPaciente['0']['estado_civil'] : '' ?>">
            <option value="">            Estado civil:  </option>
            <option value="Solteiro">    Solteiro(a)    </option>
            <option value="Casado">      Casado(a)      </option>
            <option value="Divorciado">  Divorciado(a)  </option>
            <option value="Viuvo">       Viúvo(a)       </option>
            <option value="Separado">    Separado(a)    </option>
          </select>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-2">
          <select class="form-control form-control-sm" name="sexo" id="sexo" value= "<?= isset($this->view->dadosPaciente['0']['sexo']) ? $this->view->dadosPaciente['0']['sexo'] : '' ?>">
            <option value="">  Sexo:      </option>
            <option value="M"> Masculino  </option>
            <option value="F"> Feminino   </option>
          </select>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-2">
          <select class="form-control form-control-sm" name="cor" id="cor" value= "<?= isset($this->view->dadosPaciente['0']['cor']) ? $this->view->dadosPaciente['0']['cor'] : '' ?>">
            <option value="">          Cor:       </option>
            <option value="Branco">    Branco     </option>
            <option value="Preto">     Preto      </option>
            <option value="Amarelo">   Amarelo    </option>
            <option value="Pardo">     Pardo      </option>
            <option value="Indigena">  Indígena   </option>
          </select>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-2">
          <input type="text" class="form-control form-control-sm" id="data_nascimento" name="data_nascimento" placeholder="Data de nascimento" value="<?= isset($this->view->dadosPaciente['0']['data_nascimento']) ? $this->view->dadosPaciente['0']['data_nascimento'] : '' ?>">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-2">
          <input type="text" class="form-control form-control-sm" id="cep" name="cep" placeholder="C.E.P" value="<?= isset($this->view->dadosPaciente['0']['cep']) ? $this->view->dadosPaciente['0']['cep'] : '' ?>">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-6">
          <input type="text" class="form-control form-control-sm" id="endereco" name="endereco" placeholder="Endereço" value="<?= isset($this->view->dadosPaciente['0']['endereco']) ? $this->view->dadosPaciente['0']['endereco'] : '' ?>">
        </div>
        <div class="form-group col-md-2">
          <input type="text" class="form-control form-control-sm" id="numero" name="numero" placeholder="Número" value="<?= isset($this->view->dadosPaciente['0']['numero']) ? $this->view->dadosPaciente['0']['numero'] : '' ?>">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-6">
          <input type="text" class="form-control form-control-sm" id="complemento" name="complemento" placeholder="Complemento" value="<?= isset($this->view->dadosPaciente['0']['complemento']) ? $this->view->dadosPaciente['0']['complemento'] : '' ?>">
        </div>
      </div>
      
      <div class="form-row">
        <div class="form-group col-md-6">
          <input type="text" class="form-control form-control-sm" id="bairro" name="bairro" placeholder="Bairro" value="<?= isset($this->view->dadosPaciente['0']['bairro']) ? $this->view->dadosPaciente['0']['bairro'] : '' ?>">
        </div>
      </div>
      
      <div class="form-row">
        <div class="form-group col-md-6">
          <input type="text" class="form-control form-control-sm" id="cidade" name="cidade" placeholder="Cidade" value="<?= isset($this->view->dadosPaciente['0']['cidade']) ? $this->view->dadosPaciente['0']['cidade'] : '' ?>">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-3">
          <select class="form-control form-control-sm" name="uf" id="uf" value="<?= isset($this->view->dadosPaciente['0']['uf']) ? $this->view->dadosPaciente['0']['uf'] : '' ?>"> 
            <option value="00">   Selecione o Estado   </option> 
            <option value="ac">   Acre                 </option> 
            <option value="al">   Alagoas              </option> 
            <option value="am">   Amazonas             </option> 
            <option value="ap">   Amapá                </option> 
            <option value="ba">   Bahia                </option> 
            <option value="ce">   Ceará                </option> 
            <option value="df">   Distrito Federal     </option> 
            <option value="es">   Espírito Santo       </option> 
            <option value="go">   Goiás                </option> 
            <option value="ma">   Maranhão             </option> 
            <option value="mt">   Mato Grosso          </option> 
            <option value="ms">   Mato Grosso do Sul   </option> 
            <option value="mg">   Minas Gerais         </option> 
            <option value="pa">   Pará                 </option> 
            <option value="pb">   Paraíba              </option> 
            <option value="pr">   Paraná               </option> 
            <option value="pe">   Pernambuco           </option> 
            <option value="pi">   Piauí                </option> 
            <option value="rj">   Rio de Janeiro       </option> 
            <option value="rn">   Rio Grande do Norte  </option> 
            <option value="ro">   Rondônia             </option> 
            <option value="rs">   Rio Grande do Sul    </option> 
            <option value="rr">   Roraima              </option> 
            <option value="sc">   Santa Catarina       </option> 
            <option value="se">   Sergipe              </option> 
            <option value="sp">   São Paulo            </option> 
            <option value="to">   Tocantins            </option> 
          </select>
        </div>
      </div>      
      
      <div class="form-row">
        <div class="form-group col-md-6">
          <input type="text" class="form-control form-control-sm" id="naturalidade" name="naturalidade" placeholder="Naturalidade" value="<?= isset($this->view->dadosPaciente['0']['naturalidade']) ? $this->view->dadosPaciente['0']['naturalidade'] : '' ?>">
        </div>
      </div>
      
      <div class="form-row">
        <div class="form-group col-md-2">
          <input type="text" class="form-control form-control-sm" id="telefone" name="telefone" placeholder="Telefone" value="<?= isset($this->view->dadosPaciente['0']['telefone']) ? $this->view->dadosPaciente['0']['telefone'] : '' ?>">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-2">
          <input type="text" class="form-control form-control-sm" id="celular" name="celular" placeholder="Celular" value="<?= isset($this->view->dadosPaciente['0']['celular']) ? $this->view->dadosPaciente['0']['celular'] : '' ?>">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-2">
          <input type="text" class="form-control form-control-sm" id="whatsapp" name="whatsapp" placeholder="Whatsapp" value="<?= isset($this->view->dadosPaciente['0']['whatsapp']) ? $this->view->dadosPaciente['0']['whatsapp'] : '' ?>">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-2">
          <input type="text" class="form-control form-control-sm" id="email" name="email" placeholder="E-mail" value="<?= isset($this->view->dadosPaciente['0']['email']) ? $this->view->dadosPaciente['0']['email'] : '' ?>">
        </div>
      </div>
      
      <div class="form-row">
        <div class="form-group col-md-6">
          <input type="text" class="form-control form-control-sm" id="nome_mae" name="nome_mae" placeholder="Nome da mãe" value="<?= isset($this->view->dadosPaciente['0']['nome_mae']) ? $this->view->dadosPaciente['0']['nome_mae'] : '' ?>">
        </div>
        <div class="form-group col-md-6">
          <input type="text" class="form-control form-control-sm" id="profissao_mae" name="profissao_mae" placeholder="Profissão da mãe" value="<?= isset($this->view->dadosPaciente['0']['profissao_mae']) ? $this->view->dadosPaciente['0']['profissao_mae'] : '' ?>">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-6">
          <input type="text" class="form-control form-control-sm" id="nome_pai" name="nome_pai" placeholder="Nome do pai" value="<?= isset($this->view->dadosPaciente['0']['nome_pai']) ? $this->view->dadosPaciente['0']['nome_pai'] : '' ?>">
        </div>
        <div class="form-group col-md-6">
          <input type="text" class="form-control form-control-sm" id="profissao_pai" name="profissao_pai" placeholder="Profissão do pai" value="<?= isset($this->view->dadosPaciente['0']['profissao_pai']) ? $this->view->dadosPaciente['0']['profissao_pai'] : '' ?>">
        </div>
      </div>

      <div class="form-row">
      <div class="form-group col-md-4">
        <button type="submit" class="btn btn-primary mb-2">
          <?php if(isset($this->view->operacao) and ($this->view->operacao == '/inserirPaciente') ) {
                  echo "Salvar";
                }
                else if(isset($this->view->operacao) and ($this->view->operacao == '/AlterarPaciente') ) {
                  echo "Alterar";
                } 
          ?>
        </button>
        <?php if(isset($this->view->operacao) and ($this->view->operacao == '/AlterarPaciente') ) { ?>
          <a class="btn btn-danger mb-2" href="/ExcluirPaciente?id=<?= $this->view->dadosPaciente['0']['id'] ?>" >Excluir</a>
        <?php } ?>
      </div>
      </div>


    </form>
  </div>

<?php include('../App/Views/index/footer.phtml') ?>