<div class="container-fluid h-100">
  <div class="row h-100">
    
    <div class="col-md-6 banner">
      <div class="row h-100 justify-content-center align-items-center">
        <div>
        <div class="communicationItem">
          <i class="fas fa-search fa-2x mr-3"></i>
          Consulte suas agendas de forma eficiente.
        </div>
        <div class="communicationItem">
          <i class="fas fa-user-friends fa-2x mr-3"></i>
          Tenha controle de seus pacientes.
        </div>
        <div class="communicationItem">
          <i class="far fa-comment fa-2x mr-3"></i>
          Controle suas tele-consultas.
        </div>
      </div>
    </div>
    </div>

    <div class="col-md-6 pt-4 pl-5 pr-5">
    <form method="post" action="/autenticar">
      <div class="row">
        <div class="col">
          <input type="text" name="login" class="form-control" placeholder="Login">
        </div>
        <div class="col">
          <input type="text" name="senha" class="form-control" placeholder="Senha">
        </div>
        <div class="col-auto">
          <button type="submit" class="btn btn-primary mb-2">Entrar</button> 
        </div>
      </div>
      <?php if($this->view->login == 'erro') { ?>
        <div class="row">
          <div class="col">
            <span class="text text-danger">* E-mail ou senha inválido(s) </span>
          </div>
        </div>
      <?php } ?>
    </form>

    <div class="row pt-5 pl-5 pr-5">
      <div class="col pl-5 pr-5">
        <h1 class="title">Sistema para controle de consultório.</h1>
      </div>  
    </div>


    </div>

  </div>
</div>