<?php include('../App/Views/index/header.phtml') ?>
  
  <div class="container">

    <form id="dados" method="POST" action="<?php echo $this->view->operacao; ?>">
      <div class="form-row">
        <div class="form-group col-md-2">
          <input type="text" class="form-control form-control-sm" id="id" name="id" placeholder="ID" value="<?= isset($this->view->dadosFuncionario['0']['id']) ? $this->view->dadosFuncionario['0']['id'] : '' ?>" readonly>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-2">
          <select class="form-control form-control-sm" name="status" id="status" value= "<?= isset($this->view->dadosFuncionario['0']['status']) ? $this->view->dadosFuncionario['0']['status'] : '' ?>">
            <option value="A">Ativo</option>
            <option value="I">Inativo</option>
          </select>
        </div>
      </div>       
      
      <div class="form-row">
        <div class="form-group col-md-6">
          <input type="text" class="form-control form-control-sm" id="nome" name="nome" placeholder="Digite o nome" value="<?= isset($this->view->dadosFuncionario['0']['nome']) ? $this->view->dadosFuncionario['0']['nome'] : '' ?>">
        </div>
      </div>
      
      <div class="form-row">
        <div class="form-group col-md-4">
          <input type="text" class="form-control form-control-sm" id="cpf" name="cpf" placeholder="Digite o CPF" value="<?= isset($this->view->dadosFuncionario['0']['cpf']) ? $this->view->dadosFuncionario['0']['cpf'] : '' ?>">
        </div>
        <div class="form-group col-md-4">
          <input type="text" class="form-control form-control-sm" id="rg" name="rg" placeholder="Digite o RG" value="<?= isset($this->view->dadosFuncionario['0']['rg']) ? $this->view->dadosFuncionario['0']['rg'] : '' ?>">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-4">
          <input type="text" class="form-control form-control-sm" id="carteira_trabalho" name="carteira_trabalho" placeholder="Carteira de trabalho" value="<?= isset($this->view->dadosFuncionario['0']['carteira_trabalho']) ? $this->view->dadosFuncionario['0']['carteira_trabalho'] : '' ?>">
        </div>
        <div class="form-group col-md-4">
          <input type="text" class="form-control form-control-sm" id="pis" name="pis" placeholder="Número do PIS" value="<?= isset($this->view->dadosFuncionario['0']['pis']) ? $this->view->dadosFuncionario['0']['pis'] : '' ?>">
        </div>
        <div class="form-group col-md-4">
          <input type="text" class="form-control form-control-sm" id="cnh" name="cnh" placeholder="Digite o número da CNH" value="<?= isset($this->view->dadosFuncionario['0']['cnh']) ? $this->view->dadosFuncionario['0']['cnh'] : '' ?>">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-4">
          <input type="text" class="form-control form-control-sm" id="dataAdmissao" name="dataAdmissao" placeholder="Data admissão" value="<?= isset($this->view->dadosFuncionario['0']['data_admissao']) ? $this->view->dadosFuncionario['0']['data_admissao'] : '' ?>">
        </div>
        <div class="form-group col-md-4">
          <input type="text" class="form-control form-control-sm" id="salario" name="salario" placeholder="Salário" value="<?= isset($this->view->dadosFuncionario['0']['salario']) ? $this->view->dadosFuncionario['0']['salario'] : '' ?>">
        </div>
        <div class="form-group col-md-4">
          <input type="text" class="form-control form-control-sm" id="dataDemissao" name="dataDemissao" placeholder="Data demissão" value="<?= isset($this->view->dadosFuncionario['0']['data_demissao']) ? $this->view->dadosFuncionario['0']['data_demissao'] : '' ?>">
        </div>
      </div>


      <div class="form-row">
        <div class="form-group col-md-2">
          <input type="text" class="form-control form-control-sm" id="cep" name="cep" placeholder="Cep" value="<?= isset($this->view->dadosFuncionario['0']['cep']) ? $this->view->dadosFuncionario['0']['cep'] : '' ?>">
        </div>
        <div class="form-group col-md-5">
          <input type="text" class="form-control form-control-sm" id="endereco" name="endereco" placeholder="Digite o endereço" value="<?= isset($this->view->dadosFuncionario['0']['endereco']) ? $this->view->dadosFuncionario['0']['endereco'] : '' ?>">
        </div>
        <div class="form-group col-md-5">
          <input type="text" class="form-control form-control-sm" id="complemento" name="complemento" placeholder="Digite o complemento" value="<?= isset($this->view->dadosFuncionario['0']['complemento']) ? $this->view->dadosFuncionario['0']['complemento'] : '' ?>">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-5">
          <input type="text" class="form-control form-control-sm" id="bairro" name="bairro" placeholder="Digite o bairro" value="<?= isset($this->view->dadosFuncionario['0']['bairro']) ? $this->view->dadosFuncionario['0']['bairro'] : '' ?>">
        </div>
        <div class="form-group col-md-4">
          <input type="text" class="form-control form-control-sm" id="cidade" name="cidade" placeholder="Digite a cidade" value="<?= isset($this->view->dadosFuncionario['0']['cidade']) ? $this->view->dadosFuncionario['0']['cidade'] : '' ?>">
        </div>
        <div class="form-group col-md-3">
          <select class="form-control form-control-sm" name="uf" id="uf" value="<?= isset($this->view->dadosFuncionario['0']['uf']) ? $this->view->dadosFuncionario['0']['uf'] : '' ?>"> 
            <option value="00">Selecione o Estado</option> 
            <option value="ac">Acre</option> 
            <option value="al">Alagoas</option> 
            <option value="am">Amazonas</option> 
            <option value="ap">Amapá</option> 
            <option value="ba">Bahia</option> 
            <option value="ce">Ceará</option> 
            <option value="df">Distrito Federal</option> 
            <option value="es">Espírito Santo</option> 
            <option value="go">Goiás</option> 
            <option value="ma">Maranhão</option> 
            <option value="mt">Mato Grosso</option> 
            <option value="ms">Mato Grosso do Sul</option> 
            <option value="mg">Minas Gerais</option> 
            <option value="pa">Pará</option> 
            <option value="pb">Paraíba</option> 
            <option value="pr">Paraná</option> 
            <option value="pe">Pernambuco</option> 
            <option value="pi">Piauí</option> 
            <option value="rj">Rio de Janeiro</option> 
            <option value="rn">Rio Grande do Norte</option> 
            <option value="ro">Rondônia</option> 
            <option value="rs">Rio Grande do Sul</option> 
            <option value="rr">Roraima</option> 
            <option value="sc">Santa Catarina</option> 
            <option value="se">Sergipe</option> 
            <option value="sp">São Paulo</option> 
            <option value="to">Tocantins</option> 
          </select>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-4">
          <input type="text" class="form-control form-control-sm" id="login" name="login" placeholder="Login" value="<?= isset($this->view->dadosFuncionario['0']['login']) ? $this->view->dadosFuncionario['0']['login'] : '' ?>">
        </div>
        <div class="form-group col-md-4">
          <input type="password" class="form-control form-control-sm" id="senha" name="senha" placeholder="Senha" >
        </div>
        <div class="form-group col-md-4">
          <input type="password" class="form-control form-control-sm" id="senhaConfirmada" name="senhaConfirmada" placeholder="Confirmar senha">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-4">
          <select class="form-control form-control-sm" name="perfil" id="perfil" value="<?= isset($this->view->dadosFuncionario['0']['id_perfil']) ? $this->view->dadosFuncionario['0']['id_perfil'] : '' ?>"> 
            <option value="0">perfil de usuário</option> 
            <?php if (isset($this->view->usuarios)) {
              foreach ($this->view->usuarios as $key => $value) { ?>
                <option value="<?=$value['id'] ?>"><?=$value['descricao'] ?></option> 
             <?php 
              }
            } ?>
          </select>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-4">
          <input type="text" class="form-control form-control-sm" id="telefone" name="telefone" placeholder="Telefone" value="<?= isset($this->view->dadosFuncionario['0']['telefone']) ? $this->view->dadosFuncionario['0']['telefone'] : '' ?>">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-4">
          <input type="text" class="form-control form-control-sm" id="celular" name="celular" placeholder="Celular" value="<?= isset($this->view->dadosFuncionario['0']['celular']) ? $this->view->dadosFuncionario['0']['celular'] : '' ?>">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-4">
          <input type="text" class="form-control form-control-sm" id="whats" name="whats" placeholder="WhatsApp" value="<?= isset($this->view->dadosFuncionario['0']['whatsApp']) ? $this->view->dadosFuncionario['0']['whatsApp'] : '' ?>">
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col-md-4">
          <input type="email" class="form-control form-control-sm" id="email" name="email" placeholder="E-mail" value="<?= isset($this->view->dadosFuncionario['0']['email']) ? $this->view->dadosFuncionario['0']['email'] : '' ?>">
        </div>
      </div>

       <div class="form-row">
        <div class="form-group col-md-4">
          <button type="submit" class="btn btn-primary mb-2">
            <?php if(isset($this->view->operacao) and ($this->view->operacao == '/inserirFuncionario') ) {
                    echo "Salvar";
                  }
                  else if(isset($this->view->operacao) and ($this->view->operacao == '/AlterarFuncionario') ) {
                    echo "Alterar";
                  } 
            ?>
          </button>
          <?php if(isset($this->view->operacao) and ($this->view->operacao == '/AlterarFuncionario') ) { ?>
            <a class="btn btn-danger mb-2" href="/ExcluirFuncionario?id=<?= $this->view->dadosFuncionario['0']['id'] ?>" >Excluir</a>
          <?php } ?>
        </div>
      </div>

    </form>
  </div>
<?php include('../App/Views/index/footer.phtml') ?>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.2/dist/jquery.validate.min.js"></script>

<style type="text/css">
  label.error{color: #f00; padding: 0 5px; font-size: 10pt;}
  .error {border-color: #f00; }
</style>

<script>
  $(document).ready(function(){

     // Máscaras dos campos 
     $('#cpf').mask("999.999.999-99");
     $('#rg').mask("99.999.999-9");
     $('#pis').mask("999.99999.99-9");
     $('#telefone').mask("(99)99999-9999");
     $('#celular').mask("(99)99999-9999");
     $('#whats').mask("(99)99999-9999");
     $('#cep').mask("99.999-999");
     $('#dataAdmissao').mask("99/99/9999");
     $('#dataDemissao').mask("99/99/9999");
     $('#salario').mask("R$ 999.990,00");


     // validações dos campos
     $('#dados').validate({
       rules : {
         nome : {
           required : true,
           minlength : 5
         },         
         senha : {
           rangelength : [3,10]
         },
         senhaConfirmada : {
           equalTo : "#senha"
         }

       },
       messages : {
         nome : {
           required : "É obrigatório o preenchimento desse campo.",
           minlength : "O tamanho mínimo para esse campo é 5 caracteres."
         },
         senha : {
           rangelength : "A senha deve ter entre 3 e 10 caracteres."
         },
         senhaConfirmada : {
           equalTo : "O campo não confere com o campo senha."
         }
       }
     });


     
  });
</script>


